<a href="https://colab.research.google.com/github/kumarshubham777/Logis/blob/master/python_prac.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
vector = np.array([1,2,3])
vector

array([1, 2, 3])

In [0]:
matrix = np.array([[1,2,3] , 
                   [4,5,6],
                   [7,8,9]])

In [0]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
vector.T
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [0]:
vector.T

array([1, 2, 3])

In [0]:
import pandas as pd
dataset = pd.read_csv('Salary_Data.csv')

In [0]:
dataset

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [0]:
from google.colab import drive
drive.mount('/content/drive')

KeyboardInterrupt: ignored